# Generated by Django 5.2.7 on 2026-03-30 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('heading', models.TextField(verbose_name=100)),
                ('title', models.TextField(verbose_name=10)),
                ('firstname', models.TextField(verbose_name=100)),
                ('lastname', models.TextField(verbose_name=100)),
                ('address1', models.TextField(verbose_name=100)),
                ('address2', models.TextField(verbose_name=100)),
                ('address3', models.TextField(verbose_name=100)),
                ('url', models.TextField(verbose_name=100)),
                ('emailid', models.TextField(verbose_name=100)),
                ('mobile', models.TextField(verbose_name=20)),
                ('subject', models.TextField(verbose_name=100)),
                ('query', models.TextField(verbose_name=1000)),
                ('contact_type', models.TextField(verbose_name=20)),
            ],
            options={
                'db_table': 'contact_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictDetails',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'district_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionConstituencyDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'election_constituency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageDetails',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(verbose_name=100)),
                ('sub_heading', models.CharField(verbose_name=100)),
                ('content', models.CharField(verbose_name=1000)),
                ('url', models.CharField(verbose_name=100)),
                ('type', models.CharField(verbose_name=20)),
            ],
            options={
                'db_table': 'homepage_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaDetails',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('medianame', models.TextField(verbose_name=100)),
                ('logo_url', models.TextField(verbose_name=100)),
                ('url', models.TextField(verbose_name=100)),
            ],
            options={
                'db_table': 'social_media_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VillageStreetDetails',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('ward', models.BigIntegerField(blank=True, null=True)),
                ('village_street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('town_panchayat_id', models.BigIntegerField(blank=True, null=True)),
                ('village_panchayat_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'village_street_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockDetails',
            fields=[
                ('block_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('districtDetails', models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.CASCADE, to='webapi.districtdetails')),
                ('constituency', models.ManyToManyField(related_name='blocks', to='webapi.electionconstituencydetails')),
            ],
            options={
                'db_table': 'block_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PanchayatDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('blockDetails', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.CASCADE, to='webapi.blockdetails')),
            ],
            options={
                'db_table': 'panchayat_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('service_details_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('serviceModel', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='webapi.service')),
            ],
            options={
                'db_table': 'service_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceLinks',
            fields=[
                ('service_details_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('serviceModel', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='webapi.service')),
            ],
            options={
                'db_table': 'service_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TownPanchayatDetails',
            fields=[
                ('town_panchayat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('blockDetails', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.CASCADE, to='webapi.blockdetails')),
            ],
            options={
                'db_table': 'town_panchayat_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueVillageDetails',
            fields=[
                ('village_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('blockDetails', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.CASCADE, to='webapi.blockdetails')),
                ('panchayatDetails', models.ForeignKey(blank=True, db_column='panchayat_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.panchayatdetails')),
                ('townPanchayatDetails', models.ForeignKey(blank=True, db_column='town_panchayat_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.townpanchayatdetails')),
            ],
            options={
                'db_table': 'revenue_village_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=100)),
                ('constituency', models.ForeignKey(blank=True, default=91, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_requests', to='webapi.electionconstituencydetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_id', models.BigIntegerField()),
                ('ward_number', models.CharField(max_length=50)),
                ('address_line1', models.CharField(max_length=100)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_num', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=20, null=True)),
                ('document_attachment', models.FileField(blank=True, max_length=200, null=True, upload_to='media/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('registered_mobile', models.CharField(max_length=15)),
                ('contact_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.CharField(max_length=50)),
                ('amount', models.TextField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.blockdetails')),
                ('constituency', models.ForeignKey(blank=True, default=91, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='webapi.electionconstituencydetails')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.districtdetails')),
                ('panchayat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.panchayatdetails')),
                ('service_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.servicedetails')),
                ('town_panchayat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.townpanchayatdetails')),
                ('village_street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.villagestreetdetails')),
            ],
            options={
                'db_table': 'service_request_details',
                'managed': False,
            },
        ),
    ]
