# Generated by Django 5.2.7 on 2026-03-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='districtdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='electionconstituencydetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='homepagedetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='panchayatdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='revenuevillagedetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='servicedetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='servicelinks',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='socialmediadetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='townpanchayatdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='villagestreetdetails',
            options={'managed': True},
        ),
    ]
