# Generated by Django 5.2.7 on 2026-03-30 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_alter_blockdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequestdetails',
            options={'managed': True},
        ),
    ]
