# Generated by Django 5.2.7 on 2026-09-12 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_alter_servicerequestdetails_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockdetails',
            name='constituency',
        ),
        migrations.AddField(
            model_name='blockdetails',
            name='constituency',
            field=models.ForeignKey(blank=True, default=91, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ElectionConstituencyDetails', to='webapi.electionconstituencydetails'),
        ),
    ]
